{% set version = "3.2.0a2" %}

package:
  name: plotly
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/plotly/plotly-{{ version }}.tar.gz
  sha256: cd301fff68f8d375503754780e3df22f31a3c8cea26fe08046e6222ae15ae9db

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - setuptools
    - decorator >=4.0.6
    - nbformat >=4.2
    - pytz
    - requests
    - retrying >=1.3.3
    - six

test:
  imports:
    - plotly

about:
  home: https://plot.ly/python/
  license: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.txt'
  summary: 'An interactive JavaScript-based visualization library for Python'
  description: |
    plotly.py is an interactive, open-source, and JavaScript-based graphing
    library for Python. Built on top of plotly.js, plotly.py is a high-level,
    declarative charting library that includes over 30 chart types,
    including scientific charts, 3D graphs, statistical charts, SVG maps,
    financial charts, and more.
  doc_url: https://plot.ly/python/
  dev_url: https://github.com/plotly/plotly.py

extra:
  recipe-maintainers:
    - jonmmease