package:
  name: plotly
  version: "1.3.2"

source:
  git_url: https://github.com/plotly/python-api

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - requests
    - six
  run:
    - python
    - setuptools
    - requests
    - six

about:
  home: https://plot.ly
  license: MIT
  summary: Python plotting library for collaborative, interactive, publication-quality graphs.
